admin_index:
    path: /
    defaults: { _controller: SimpleITClaireExerciseBundle:Frontend/Admin:index }
admin_list_disable:
    path: /users/disable
    defaults: { _controller: SimpleITClaireExerciseBundle:Frontend/Admin:listDisable }
admin_preview_user:
    path: /preview/user/{user}
    defaults: { _controller: SimpleITClaireExerciseBundle:Frontend/Admin:preview , user:null}
admin_list_users:
    path: /users/all
    defaults: { _controller: SimpleITClaireExerciseBundle:Frontend/Admin:all }
admin_change:
    path: /users/change
    defaults: { _controller: SimpleITClaireExerciseBundle:Frontend/Admin:change }
admin_edit:
    path: /users/change/{user}
    defaults: { _controller: SimpleITClaireExerciseBundle:Frontend/Admin:edit }
admin_update_password:
    path: /users/password/{user}
    defaults: { _controller: SimpleITClaireExerciseBundle:Frontend/Admin:updatePassword }
admin_migrate:
    path: /migrate
    defaults: { _controller: SimpleITClaireExerciseBundle:Frontend/Admin:migrate }
admin_show_aur:
    path: /users/aur/
    #defaults: { _controller: SimpleITClaireExerciseBundle:Frontend/Admin:showAUR, user:null }
    defaults: { _controller: SimpleITClaireExerciseBundle:Frontend/Admin:showAUR}

admin_importlocal:
    path: /import/local
    defaults: { _controller: SimpleITClaireExerciseBundle:Frontend/Admin:importLocal }
