admin_export:
    path: /
    defaults: { _controller: SimpleITClaireExerciseBundle:Frontend/Export:export }

export_filters_directory:
    path: /directory/filter/{directory}/
    defaults: { _controller: SimpleITClaireExerciseBundle:Frontend/Export:filterDirectory}


export_create_qcm:
    path: /directory/export/{model}
    defaults: { _controller: SimpleITClaireExerciseBundle:Frontend/Export:createQcm }
