admin_export:
    pattern: /
    defaults: { _controller: SimpleITClaireExerciseBundle:Frontend/Export:export }

export_filters_directory:
    pattern: /directory/filter/{directory}/
    defaults: { _controller: SimpleITClaireExerciseBundle:Frontend/Export:filterDirectory}


export_create_qcm:
    pattern: /directory/export/{model}
    defaults: { _controller: SimpleITClaireExerciseBundle:Frontend/Export:createQcm }
