frontend_index:
    path: /
    defaults: { _controller: SimpleITClaireExerciseBundle:Frontend/Frontend:index }
frontend_password:
    path: /update/mypassword
    defaults: { _controller: SimpleITClaireExerciseBundle:Frontend/Frontend:updatePassword }
