admin_stats:
    path: /
    defaults: { _controller: SimpleITClaireExerciseBundle:Frontend/Stat:stat }

admin_filters_directory:
    path: /filter/{directory}/{view}
    defaults: { _controller: SimpleITClaireExerciseBundle:Frontend/Stat:filterDirectory, view:0 }

admin_stats_directory:
    path: /directory/frame/{directory}/{view}
    defaults: { _controller: SimpleITClaireExerciseBundle:Frontend/Stat:statDirectory, view:0 }

admin_stats_personal:
    path: /personal/{directory}/{user}/{view}
    defaults: { _controller: SimpleITClaireExerciseBundle:Frontend/Stat:statPersonal, view:0 }

admin_stats_detail:
    path: /detail/{directory}/{user}/{view}
    defaults: { _controller: SimpleITClaireExerciseBundle:Frontend/Stat:statDetail, view:0 }

admin_stats_create_view:
    path: /directory/createView/{directory}
    defaults: { _controller: SimpleITClaireExerciseBundle:Frontend/Stat:createView}
admin_stats_delete_view:
    path: /directory/deleteView/{view}
    defaults: { _controller: SimpleITClaireExerciseBundle:Frontend/Stat:deleteView, view:0}
    methods: [DELETE]
admin_stats_fullfill:
    path: /directory/fullfill/{directory}/{view}
    defaults: { _controller: SimpleITClaireExerciseBundle:Frontend/Stat:fullFill, directory:0,view:0}
    methods: [GET]
admin_stats_edit_view:
    path: /directory/editView/{view}
    defaults: { _controller: SimpleITClaireExerciseBundle:Frontend/Stat:editView}
admin_stats_export_directory:
    path: /directory/export-directory/{directory}/{model}/{view}
    defaults: { _controller: SimpleITClaireExerciseBundle:Frontend/Stat:exportModel, view:0}
admin_test_dunno:
    path: /directory/export-directory/{view}/
    defaults: { _controller: SimpleITClaireExerciseBundle:Frontend/Stat:exportModel, view:0}
