imports:
    - { resource: comper_secrets.yml }
parameters:
    comper_lrs_endpoint: https://compervm-dev.liris.cnrs.fr/trax/api/gateway/clients/default/stores/default/xapi/statements
    comper_jwt_key_path: jwtRS256.key
    comper_api_url: https://compervm-dev.liris.cnrs.fr/cpe/api/old/
    comper_profile_endpoint: https://compervm-dev.liris.cnrs.fr/cpe/api/old/profile/to-olm
    comper_profile_create_endpoint: https://compervm-dev.liris.cnrs.fr/cpe/api/old/profile/create
    comper_group_create_endpoint: https://compervm-dev.liris.cnrs.fr/cpe/api/old/group/create
    comper_teacher_manager_endpoint: https://compervm-dev.liris.cnrs.fr/cpe/api/old/profile/addTeacher
services:
    app.jwtService:
        class:     SimpleIT\ClaireExerciseBundle\Service\JwtService
        arguments: ['%comper_jwt_key_path%', '%kernel.root_dir%']
    app.statementFactoryService:
        class:     SimpleIT\ClaireExerciseBundle\Service\StatementFactoryService
        arguments: ['%comper_lrs_endpoint%', '%comper_lrs_creds%']
    app.profileService:
        class: SimpleIT\ClaireExerciseBundle\Service\ProfileService
        arguments: ['%comper_profile_endpoint%', '%comper_profile_create_endpoint%', '%comper_group_create_endpoint%', '%comper_teacher_manager_endpoint%', '@app.jwtService']

