# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    app.form.askerUser:
        class: SimpleIT\ClaireExerciseBundle\Form\AskerUserType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type }
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
