# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    app.form.askerUser:
        class: SimpleIT\ClaireExerciseBundle\Form\AskerUserType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type }
    app.jwtService:
        class:     SimpleIT\ClaireExerciseBundle\Service\JwtService
        arguments: ['%comper_jwt_key_path%', '%kernel.root_dir%']
    app.statementFactoryService:
        class:     SimpleIT\ClaireExerciseBundle\Service\StatementFactoryService
        arguments: ['%comper_lrs_endpoint%', '%comper_lrs_creds%']
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
