<?php

namespace SimpleIT\ClaireExerciseBundle\Repository;

/**
 * AskerUserDirectoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AskerUserDirectoryRepository extends \Doctrine\ORM\EntityRepository
{
    public function nativeAll(){
        $sql = "
            SELECT d.name, user_id, isManager, d.owner_id
            FROM asker_user_directory aud
            JOIN directory d
            ON d.id = aud.directory_id
            WHERE d.parent_id is null
            ORDER BY user_id, d.name
        ";
       $stmt = $this->getEntityManager()->getConnection()->prepare($sql);
       $stmt->execute();
       return $stmt->fetchAll();
       # new version is doctine is up to date
       #return $stmt->executeQuery()->fetchAllAssociative();
    }
    public function findObjectParents()
    {
        return $this->createQueryBuilder('aud')
            ->join('aud.directory','d')
            ->where('d.parent is NULL')
            //->groupBy('d.name')
        ;
    }
    public function findMyParents($user)
    {
        return $this->createQueryBuilder('aud')
            ->join('aud.directory','d')
            #->where('d.parent is NULL')
            ->where('aud.user = :user')
            ->setParameter('user',$user)
            ->getQuery()
            ->getResult()
        ;
    }

    public function findByUserIdDir($userId,$directory)
    {
        return $this->createQueryBuilder('aud')
                    ->join('aud.user', 'u')
                    ->where('u.id = :userid')
                    ->andWhere('aud.directory= :directory')
                    ->setParameter('userid', $userId)
                    ->setParameter('directory', $directory->getId())
                    ->getQuery()
                ->getOneOrNullResult()
            ;
    }

    public function findByUsernameDir($username,$directory)
    {
        return $this->createQueryBuilder('aud')
                    ->join('aud.user', 'u')
                    ->where('u.username = :username')
                    ->andWhere('aud.directory= :directory')
                    ->setParameter('username', $username)
                    ->setParameter('directory', $directory->getId())
                    ->getQuery()
                ->getOneOrNullResult()
            ;
    }

}

