<?php

namespace SimpleIT\ClaireExerciseBundle\Repository;

/**
 * AskerUser2Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AskerUserRepository extends \Doctrine\ORM\EntityRepository
{
}
