<?php

namespace SimpleIT\ClaireExerciseBundle\Repository;

/**
 * PedagogicRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PedagogicRepository extends \Doctrine\ORM\EntityRepository
{

    public function periodByCode($code)
    {
        return $this->createQueryBuilder('p')
            ->select('p.period, p.year')
            ->where('p.code = :code')
            ->setParameter('code', $code)
            ->getQuery()
            ->getResult()
        ;
    }
}
