<?php

namespace SimpleIT\ClaireExerciseBundle\Repository;

/**
 * StatViewRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatViewRepository extends \Doctrine\ORM\EntityRepository
{
}
