<?php

namespace SimpleIT\ClaireExerciseBundle\Entity;

/**
 * ExerciseModelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExerciseModelRepository extends \Doctrine\ORM\EntityRepository
{
}
