<?php

namespace CRT\ToolBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AcademyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AcademyRepository extends EntityRepository
{
    public function findPreferred()
    {
        $qb = $this->createQueryBuilder('a');
        return $qb
            ->where("a.ldapName !=  'Prestataire'")
            ->getQuery()
            ->getResult()
        ;

    }

}
