<?php

namespace CRT\ToolBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CorporateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CorporateRepository extends EntityRepository
{
}
