<?php

namespace CRT\ToolBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RequestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RequestRepository extends EntityRepository
{
    public function findOlds($status, $expireDate)
    {
        return $this->createQueryBuilder('r')
            ->where('r.status = :status')
            ->setParameter('status', $status)
            ->andWhere('r.createDate < :expireDate')
            ->setParameter('expireDate', $expireDate)
            ->getQuery()
            ->getResult()
        ;
    }

    public function findWaitingByToken($token, $waiting)
    {
        return $this->createQueryBuilder('r')
            ->where('r.status = :status')
            ->setParameter('status', $waiting)
            ->andWhere('r.token = :token')
            ->setParameter('token', $token)
            ->getQuery()
            ->getOneOrNullResult()
        ;
    }
}
