<?php

namespace CRT\ToolBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RequestStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RequestStatusRepository extends EntityRepository
{
}
