api_attempt_list:
    path:  /
    defaults: { _controller: SimpleITClaireExerciseBundle:Api/CreatedExercise/Attempt:list }
    methods: [GET]
    requirements:
        _format: json

api_attempt_view:
    path:  /{attemptId}
    defaults: { _controller: SimpleITClaireExerciseBundle:Api/CreatedExercise/Attempt:view }
    methods: [GET]
    requirements:
        _format: json
        attemptId: \d+

api_item_list_by_attempt:
    path:  /{attemptId}/items/
    defaults: { _controller: SimpleITClaireExerciseBundle:Api/CreatedExercise/ItemByAttempt:list }
    methods: [GET]
    requirements:
        _format: json
        attemptId: \d+

api_item_view_by_attempt:
    path:  /{attemptId}/items/{itemId}
    defaults: { _controller: SimpleITClaireExerciseBundle:Api/CreatedExercise/ItemByAttempt:view }
    methods: [GET]
    requirements:
        _format: json
        attemptId: \d+

api_answer_list_by_item_by_attempt:
    path:  /{attemptId}/items/{itemId}/answers/
    defaults: { _controller: SimpleITClaireExerciseBundle:Api/CreatedExercise/AnswerByItemByAttempt:list }
    methods: [GET]
    requirements:
        _format: json
        attemptId: \d+
        itemId: \d+

api_answer_create_by_item_by_attempt:
    path:  /{attemptId}/items/{itemId}/answers/
    defaults: { _controller: SimpleITClaireExerciseBundle:Api/CreatedExercise/AnswerByItemByAttempt:create }
    methods: [POST]
    requirements:
        _format: json
        attemptId: \d+
        itemId: \d+
