#deadcode 27/11/2019
#api_directory_new_list:
#    path:  /new/{user}
#    defaults: { _controller: SimpleITClaireExerciseBundle:Api/Directory/Directory:newInDirectory }
#    methods: [GET]
#    requirements:
#        _format: json
api_directory_delete:
    path:  /{directoryId}
    defaults: { _controller: SimpleITClaireExerciseBundle:Api/Directory/Directory:delete }
    methods: [DELETE]
    requirements:
        _format: json
        resourceId: \d+
api_directory_clear_student:
    path:  /clear/student/{directory}
    defaults: { _controller: SimpleITClaireExerciseBundle:Api/Directory/Directory:clearStudent }
    methods: [GET]
api_directory_list:
    path:  /
    defaults: { _controller: SimpleITClaireExerciseBundle:Api/Directory/Directory:list }
    methods: [GET]
    requirements:
        _format: json
api_directory_create:
    path:  /{id}
    defaults: { _controller: SimpleITClaireExerciseBundle:Api/Directory/Directory:create,id:0 }
    methods: [POST]
    requirements:
        _format: json
api_directory_mine:
    path:  /mine/
    defaults: { _controller: SimpleITClaireExerciseBundle:Api/Directory/Directory:mine }
    methods: [GET]
    requirements:
        _format: json
api_directory_edit:
    path:  /{directoryId}
    defaults: { _controller: SimpleITClaireExerciseBundle:Api/Directory/Directory:edit }
    methods: [PUT]
    requirements:
        _format: json
        exercise_modelId: \d+
api_directory_view:
    path:  /mine/{directoryId}
    defaults: { _controller: SimpleITClaireExerciseBundle:Api/Directory/Directory:view }
    methods: [GET]
    requirements:
        _format: json
        exerciseModelId: \d+
api_directory_view_exercises:
    path:  /{directoryId}
    defaults: { _controller: SimpleITClaireExerciseBundle:Api/Directory/Directory:viewExercises }
    methods: [GET]
api_directory_model:
    path:  /model/{model}
    defaults: { _controller: SimpleITClaireExerciseBundle:Api/Directory/Directory:model}
    methods: [GET]
    requirements:
        _format: json
api_directory_model_save:
    path:  /model/{model}/{directory}
    defaults: { _controller: SimpleITClaireExerciseBundle:Api/Directory/Directory:modelDirectory}
    methods: [POST]
    requirements:
        _format: json

api_directory_visible:
    path:  /visible/{directory}
    defaults: { _controller: SimpleITClaireExerciseBundle:Api/Directory/Directory:visible}
    methods: [PUT]
    requirements:
        _format: json
api_directory_clone:
    path:  /clone/{directory}
    defaults: { _controller: SimpleITClaireExerciseBundle:Api/Directory/Directory:clone}
    methods: [POST]
    requirements:
        _format: json
api_directory_duplicate:
    path:  /{directory}/duplicate
    defaults: { _controller: SimpleITClaireExerciseBundle:Api/Directory/Directory:duplicate }
    methods: [POST]
    requirements:
        _format: json
        resourceId: \d+

api_directory_jwt:
    path: /jwt/{frameworkId}/{role}
    defaults: { _controller: SimpleITClaireExerciseBundle:Api/Directory/Directory:jwt}
    methods: [GET]

api_directory_jwt_group:
    path: /jwt/{frameworkId}/{groupId}/{role}
    defaults: { _controller: SimpleITClaireExerciseBundle:Api/Directory/Directory:jwtGroup}
    methods: [GET]

api_directory_users:
    path: /comper/{directoryId}/users
    defaults: { _controller: SimpleITClaireExerciseBundle:Api/Directory/Directory:listUsers }
    methods: [ GET ]

api_directory_createGroup:
    path: /comper/{directoryId}/createGroup
    defaults: { _controller: SimpleITClaireExerciseBundle:Api/Directory/Directory:createGroup }
    methods: [ PUT ]

api_directory_comper:
    path: /comper/{directoryId}
    defaults: { _controller: SimpleITClaireExerciseBundle:Api/Directory/Directory:activateComper }
    methods: [ GET ]

api_directory_comper_user:
    path: /comper/{directoryId}/{userId}
    defaults: { _controller: SimpleITClaireExerciseBundle:Api/Directory/Directory:activateComperUser }
    methods: [ GET ]

api_directory_comper_add_managers:
    path: /comper/{directoryId}/managers/addManagers/
    defaults: { _controller: SimpleITClaireExerciseBundle:Api/Directory/Directory:activateComperManagers }
    methods: [ GET ]
