api_profile_root:
    pattern: /
api_profile_request:
    pattern: /request/{framework_id}
    defaults: {_controller: SimpleITClaireExerciseBundle:Api/Profile/Profile:requestProfile}
    methods: [GET]

api_profile_specific_request:
    pattern: /request/{framework_id}/user/{userId}
    defaults: {_controller: SimpleITClaireExerciseBundle:Api/Profile/Profile:requestSpecificProfile}
    methods: [GET]

api_profile_trace:
    pattern: /trace/{directoryId}/{action}
    defaults: {_controller: SimpleITClaireExerciseBundle:Api/Profile/Profile:trace}
    methods: [POST]

