api_profile_root:
    path: /
api_profile_request:
    path: /request/{framework_id}
    defaults: {_controller: SimpleITClaireExerciseBundle:Api/Profile/Profile:requestProfile}
    methods: [GET]

api_profile_update:
    path: /update/{framework_id}
    defaults: {_controller: SimpleITClaireExerciseBundle:Api/Profile/Profile:updateProfile}
    methods: [GET]

api_profile_specific_request:
    path: /request/{framework_id}/user/{userId}
    defaults: {_controller: SimpleITClaireExerciseBundle:Api/Profile/Profile:requestSpecificProfile}
    methods: [GET]

api_profile_trace:
    path: /trace/{directoryId}/{action}
    defaults: {_controller: SimpleITClaireExerciseBundle:Api/Profile/Profile:trace}
    methods: [POST]

