api_recommendation_send_statement:
    pattern: /statement/{recommendationTitle}
    defaults: { _controller: SimpleITClaireExerciseBundle:Api/Recommendation/Recommendation:sendStatement}
    methods: [POST]