api_upload_image:
    path:  /upload-image
    defaults: { _controller: SimpleITClaireExerciseBundle:Api/ExerciseResource/Resource:uploadImage }
    methods: [POST]
    requirements:
        _format: json
