api_user_list:
    path:  /
    defaults: { _controller: SimpleITClaireExerciseBundle:Api/User/User:list }
    methods: [GET]
    requirements:
        _format: json

api_user_view:
    path:  /{userId}
    defaults: { _controller: SimpleITClaireExerciseBundle:Api/User/User:view }
    methods: [GET]
    requirements:
        _format: json
        userId: \d+

api_user_available_managers:
    path:  /available/managers
    defaults: { _controller: SimpleITClaireExerciseBundle:Api/User/User:availableManagers }
    methods: [GET]
    requirements:
        _format: json
